name: flutter_app3
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/staff_logo.png
    - assets/image/product1.jpeg
    - assets/image/product2.jpeg
    - assets/image/product3.jpeg
    - assets/image/product4.jpeg
    - assets/image/product5.jpeg
    - assets/image/product6.jpeg